Remove hard-coded prefix on container group name
SaladTechnologies/virtual-kubelet-saladcloud pull request #36
Opened 2023-11-08 23:42 UTC by dtroyer-salad

We have project names to disambiguate these on the SCE side and
namespaces on the K8s side.

Signed-off-by: Dean Troyer <dean.troyer@salad.com>

2023-11-28 22:36 UTC, dtroyer-salad commented
Rebased and refreshed on top of the now-merged Dependabot updates.  This is the branch used in the demos.

2023-11-29 17:29 UTC, seniorquico requested changes

2023-11-29 17:29 UTC, seniorquico commented on demo/qr.yaml
> +              cpu: 2
```suggestion
              cpu: "2"
```

2023-11-29 17:29 UTC, seniorquico commented on demo/qr.yaml
>                cpu: 2
```suggestion
              cpu: "2"
```

2023-11-29 21:00 UTC, seniorquico approved these changes

2023-11-29 21:00 UTC, merged